# Generated by Django 5.2.8 on 2025-12-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companioninsight',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
