# Generated by Django 5.2.8 on 2025-12-02 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_business_email_fields"),
        ("companion", "0002_companioninsight_dismissed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanionSuggestedAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action_type",
                    models.CharField(
                        choices=[("bank_match_review", "Bank match review")],
                        default="bank_match_review",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("applied", "Applied"), ("dismissed", "Dismissed")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("confidence", models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ("summary", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggested_actions",
                        to="companion.healthindexsnapshot",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companion_actions",
                        to="core.business",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
