# Generated by Django 5.2.8 on 2025-12-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0005_companion_depends_on_core_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacecompanionprofile',
            name='last_seen_bank_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacecompanionprofile',
            name='last_seen_dashboard_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacecompanionprofile',
            name='last_seen_expenses_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacecompanionprofile',
            name='last_seen_invoices_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacecompanionprofile',
            name='last_seen_reconciliation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
