# Generated by Django 5.2.8 on 2025-12-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companion", "0007_companionsuggestedaction_severity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacecompanionprofile",
            name="last_seen_reports_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspacecompanionprofile",
            name="last_seen_tax_fx_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

