# Generated by Django 5.2.8 on 2025-12-19

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor) -> None:
    ProvisionalLedgerEvent = apps.get_model("companion", "ProvisionalLedgerEvent")
    AICommandRecord = apps.get_model("companion", "AICommandRecord")
    ContentType = apps.get_model("contenttypes", "ContentType")

    # Status rename: accepted -> applied
    ProvisionalLedgerEvent.objects.filter(status="accepted").update(status="applied")

    # Best-effort backfill bank_transaction from generic subject pointer.
    bank_tx_ct = ContentType.objects.filter(app_label="core", model="banktransaction").first()
    if bank_tx_ct:
        ProvisionalLedgerEvent.objects.filter(
            bank_transaction__isnull=True,
            subject_content_type_id=bank_tx_ct.id,
            subject_object_id__isnull=False,
        ).update(bank_transaction_id=models.F("subject_object_id"))

    # Best-effort backfill source_command using the first Propose* command record linked to the event.
    # This keeps the "primary intent" handy even when multiple command records exist.
    for event in ProvisionalLedgerEvent.objects.filter(source_command__isnull=True).iterator():
        record = (
            AICommandRecord.objects.filter(shadow_event_id=event.id, command_type__startswith="Propose")
            .order_by("created_at")
            .first()
        )
        if record:
            ProvisionalLedgerEvent.objects.filter(id=event.id).update(source_command_id=record.id)


def backwards(apps, schema_editor) -> None:
    ProvisionalLedgerEvent = apps.get_model("companion", "ProvisionalLedgerEvent")

    # Reverse status rename: applied -> accepted
    ProvisionalLedgerEvent.objects.filter(status="applied").update(status="accepted")


class Migration(migrations.Migration):
    dependencies = [
        ("companion", "0009_aicircuitbreakerevent_businesspolicy_and_more"),
        ("core", "0057_companion_shadow_permissions"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisionalledgerevent",
            name="bank_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companion_shadow_events",
                to="core.banktransaction",
            ),
        ),
        migrations.AddField(
            model_name="provisionalledgerevent",
            name="source_command",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_shadow_event",
                to="companion.aicommandrecord",
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]

