# Generated by Django 5.2.8 on 2025-11-15 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service')], default='SERVICE', max_length=20)),
                ('sku', models.CharField(blank=True, help_text='Optional SKU or internal code.', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.business')),
                ('income_category', models.ForeignKey(blank=True, limit_choices_to={'type': 'INCOME'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.category')),
            ],
            options={
                'verbose_name': 'Product / Service',
                'verbose_name_plural': 'Products & Services',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('business', 'name'), name='unique_item_name_per_business')],
            },
        ),
    ]
