# Generated by Django 5.2.8 on 2025-11-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_bankaccount_bankstatementimport_banktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementimport',
            name='file_format',
            field=models.CharField(choices=[('generic_amount', 'Generic (Date, Description, Amount)'), ('generic_debit_credit', 'Generic (Date, Description, Debit, Credit)')], default='generic_amount', max_length=32),
        ),
    ]
