# Generated by Django 5.2.8 on 2025-11-19 09:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def backfill_invoice_amounts(apps, schema_editor):
    Invoice = apps.get_model("core", "Invoice")
    for invoice in Invoice.objects.all().iterator():
        total = invoice.total_amount or Decimal("0.00")
        if invoice.status == "PAID":
            paid = total
        else:
            paid = Decimal("0.00")
        balance = total - paid
        Invoice.objects.filter(pk=invoice.pk).update(
            amount_paid=paid,
            balance=balance,
        )


def backfill_expense_amounts(apps, schema_editor):
    Expense = apps.get_model("core", "Expense")
    for expense in Expense.objects.all().iterator():
        total = expense.amount or Decimal("0.00")
        if expense.status == "PAID":
            paid = total
        else:
            paid = Decimal("0.00")
        balance = total - paid
        Expense.objects.filter(pk=expense.pk).update(
            amount_paid=paid,
            balance=balance,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_account_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Total amount allocated via reconciliation matches.', max_digits=19),
        ),
        migrations.AddField(
            model_name='expense',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('PARTIAL', 'Partially allocated'), ('MATCHED_SINGLE', 'Matched (single entry)'), ('MATCHED_MULTI', 'Matched (multi entry)'), ('EXCLUDED', 'Excluded'), ('CREATED', 'Created (legacy)'), ('MATCHED', 'Matched (legacy)')], db_index=True, default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially paid'), ('PAID', 'Paid')], default='UNPAID', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PARTIAL', 'Partially paid'), ('PAID', 'Paid'), ('VOID', 'Void')], default='DRAFT', max_length=10),
        ),
        migrations.CreateModel(
            name='BankReconciliationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_amount', models.DecimalField(decimal_places=4, help_text='Absolute value allocated from the bank transaction.', max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.banktransaction')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_matches', to='core.journalentry')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('matched_amount__gt', 0)), name='brm_amount_positive')],
            },
        ),
        migrations.RunPython(backfill_invoice_amounts, migrations.RunPython.noop),
        migrations.RunPython(backfill_expense_amounts, migrations.RunPython.noop),
    ]
