# Generated by Django 5.2.8 on 2025-11-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0019_banktransaction_allocated_amount_expense_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='allocation_operation_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('allocation_operation_id__isnull', False)), fields=('allocation_operation_id',), name='unique_allocation_operation_id'),
        ),
    ]
