# Generated by Django 5.2.8 on 2025-11-19 10:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def populate_initial_totals(apps, schema_editor):
    Invoice = apps.get_model("core", "Invoice")
    Expense = apps.get_model("core", "Expense")

    for invoice in Invoice.objects.all().iterator():
        net = invoice.total_amount or Decimal("0.00")
        tax = invoice.tax_amount or Decimal("0.00")
        Invoice.objects.filter(pk=invoice.pk).update(
            net_total=net,
            tax_total=tax,
            grand_total=net + tax,
        )

    for expense in Expense.objects.all().iterator():
        net = expense.amount or Decimal("0.00")
        tax = expense.tax_amount or Decimal("0.00")
        Expense.objects.filter(pk=expense.pk).update(
            net_total=net,
            tax_total=tax,
            grand_total=net + tax,
        )


def seed_default_tax_rates(apps, schema_editor):
    Business = apps.get_model("core", "Business")
    TaxRate = apps.get_model("core", "TaxRate")

    for business in Business.objects.all().iterator():
        no_tax, _ = TaxRate.objects.get_or_create(
            business=business,
            code="NONE",
            defaults={
                "name": "No tax",
                "percentage": Decimal("0.00"),
                "is_recoverable": False,
                "is_default_purchases": True,
                "is_active": True,
            },
        )
        standard, _ = TaxRate.objects.get_or_create(
            business=business,
            code="GST13",
            defaults={
                "name": "GST/HST 13%",
                "percentage": Decimal("13.00"),
                "is_recoverable": True,
                "is_default_sales": True,
                "is_active": True,
            },
        )
        if not TaxRate.objects.filter(business=business, is_default_sales=True).exists():
            standard.is_default_sales = True
            standard.save(update_fields=["is_default_sales"])
        if not TaxRate.objects.filter(business=business, is_default_purchases=True).exists():
            no_tax.is_default_purchases = True
            no_tax.save(update_fields=["is_default_purchases"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_journalentry_allocation_operation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='net_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='net_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_recoverable', models.BooleanField(default=True)),
                ('is_default_sales', models.BooleanField(default=False)),
                ('is_default_purchases', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.CharField(default='CA', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='core.business')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.taxrate'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.taxrate'),
        ),
        migrations.AddConstraint(
            model_name='taxrate',
            constraint=models.UniqueConstraint(fields=('business', 'code'), name='unique_tax_code_per_business'),
        ),
        migrations.AddConstraint(
            model_name='taxrate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_sales', True)), fields=('business',), name='unique_default_sales_tax'),
        ),
        migrations.AddConstraint(
            model_name='taxrate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_purchases', True)), fields=('business',), name='unique_default_purchase_tax'),
        ),
        migrations.RunPython(populate_initial_totals, migrations.RunPython.noop),
        migrations.RunPython(seed_default_tax_rates, migrations.RunPython.noop),
    ]
