# Generated by Django 5.2.8 on 2025-11-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_expense_grand_total_expense_net_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='fiscal_year_start',
            field=models.CharField(default='01-01', max_length=5),
        ),
    ]
