# Generated by Django 5.2.8 on 2025-11-21 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_business_fiscal_year_start'),
        ('taxes', '0005_transactionlinetaxdetail_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='tax_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='taxes.taxgroup'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='taxes.taxgroup'),
        ),
    ]
