# Generated by Django 5.2.8 on 2025-11-21 09:45

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_expense_tax_group_invoice_tax_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankreconciliationmatch',
            options={'ordering': ['-reconciled_at', 'id']},
        ),
        migrations.AddField(
            model_name='bankreconciliationmatch',
            name='adjustment_journal_entry',
            field=models.ForeignKey(blank=True, help_text='Optional adjustment entry for fees or FX discrepancies', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_match_adjustments', to='core.journalentry'),
        ),
        migrations.AddField(
            model_name='bankreconciliationmatch',
            name='match_confidence',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='0.00 to 1.00, where 1.00 is deterministic match', max_digits=3),
        ),
        migrations.AddField(
            model_name='bankreconciliationmatch',
            name='match_type',
            field=models.CharField(choices=[('ONE_TO_ONE', 'One bank transaction to one journal entry'), ('ONE_TO_MANY', 'One bank transaction split across multiple entries'), ('MANY_TO_ONE', 'Multiple bank transactions to one entry'), ('MANY_TO_MANY', 'Complex multi-to-multi match')], default='ONE_TO_ONE', max_length=20),
        ),
        migrations.AddField(
            model_name='bankreconciliationmatch',
            name='reconciled_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankreconciliationmatch',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_reconciliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bankreconciliationmatch',
            index=models.Index(fields=['bank_transaction', 'reconciled_at'], name='core_bankre_bank_tr_d64698_idx'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliationmatch',
            index=models.Index(fields=['journal_entry'], name='core_bankre_journal_0e5569_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankreconciliationmatch',
            constraint=models.CheckConstraint(condition=models.Q(('match_confidence__gte', 0), ('match_confidence__lte', 1)), name='brm_confidence_range'),
        ),
    ]
