# Generated by Django 5.2.8 on 2025-11-21 10:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_enhance_bank_reconciliation_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='is_reconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalline',
            name='is_reconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalline',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReconciliationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_start_date', models.DateField()),
                ('statement_end_date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('closing_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_sessions', to='core.bankaccount')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_sessions', to='core.business')),
            ],
            options={
                'ordering': ['-statement_end_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='reconciliation_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='core.reconciliationsession'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='reconciliation_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='core.reconciliationsession'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationsession',
            constraint=models.UniqueConstraint(fields=('bank_account', 'statement_start_date', 'statement_end_date'), name='uniq_reco_session_per_period'),
        ),
    ]
