# Generated by Django 5.2.8 on 2025-11-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_bankrule_category_label_bankrule_auto_confirm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bank_setup_completed',
            field=models.BooleanField(default=False),
        ),
    ]
