# Generated by Django 5.2.8 on 2025-12-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_invoice_email_last_error_invoiceemaillog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='email_from',
            field=models.EmailField(blank=True, help_text='Default From address for outgoing invoices (e.g. billing@mycompany.com).', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='reply_to_email',
            field=models.EmailField(blank=True, help_text='Reply-to address for invoice emails (optional).', max_length=255),
        ),
    ]
