# Generated by Django 5.2.8 on 2025-12-02
# Data migration to ensure safe defaults for existing tax data

from django.db import migrations


def set_tax_defaults(apps, schema_editor):
    """
    Backfill existing TaxRate and Business records with safe defaults.
    This ensures existing data works correctly with the new tax system.
    """
    TaxRate = apps.get_model('core', 'TaxRate')
    Business = apps.get_model('core', 'Business')
    
    # Ensure existing tax rates are active and apply to both sales and purchases
    # These are sensible defaults that maintain existing behavior
    TaxRate.objects.filter(is_active__isnull=True).update(is_active=True)
    TaxRate.objects.filter(applies_to_sales__isnull=True).update(applies_to_sales=True)
    TaxRate.objects.filter(applies_to_purchases__isnull=True).update(applies_to_purchases=True)
    
    # Ensure businesses without explicit tax registration remain unregistered
    # This preserves the pre-tax-system behavior
    Business.objects.filter(is_tax_registered__isnull=True).update(is_tax_registered=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_taxrate_extended_fields'),
    ]

    operations = [
        migrations.RunPython(set_tax_defaults, migrations.RunPython.noop),
    ]
