# Generated by Django 5.2.8 on 2025-12-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_companion_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_suspense',
            field=models.BooleanField(default=False, help_text='Mark as a suspense/clearing account for close-readiness checks.'),
        ),
        migrations.AlterField(
            model_name='companionissue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
