# Generated by Django 5.2.8 on 2025-12-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_highriskaudit"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="tax_filing_due_day",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Day of month when tax return is due (e.g., 30 = end of next month).",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="tax_filing_frequency",
            field=models.CharField(
                choices=[
                    ("MONTHLY", "Monthly"),
                    ("QUARTERLY", "Quarterly"),
                    ("ANNUAL", "Annual"),
                ],
                default="QUARTERLY",
                max_length=16,
            ),
        ),
    ]
