# Generated by Django 5.2.8 on 2025-12-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_business_tax_registrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="ship_from_jurisdiction_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="invoice",
            name="ship_to_jurisdiction_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="invoice",
            name="customer_location_jurisdiction_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="invoice",
            name="place_of_supply_hint",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AUTO", "Auto"),
                    ("TPP", "Goods (TPP)"),
                    ("SERVICE", "Service"),
                    ("IPP", "Intangible (IPP)"),
                ],
                default="AUTO",
                help_text="Optional override to guide place-of-supply logic (AUTO/TPP/SERVICE/IPP).",
                max_length=12,
            ),
        ),
    ]

