# Generated by Django 5.2.8 on 2025-12-16 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_business_tax_regime_ca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('SYSTEM_ADMIN', 'System Admin'), ('CONTROLLER', 'Controller'), ('CASH_MANAGER', 'Cash Manager'), ('AP_SPECIALIST', 'AP Specialist'), ('AR_SPECIALIST', 'AR Specialist'), ('BOOKKEEPER', 'Bookkeeper'), ('VIEW_ONLY', 'View Only'), ('EXTERNAL_ACCOUNTANT', 'External Accountant'), ('AUDITOR', 'Auditor')], default='BOOKKEEPER', max_length=32)),
                ('department', models.CharField(blank=True, help_text="Department for ABAC scoping (e.g., 'Marketing', 'Engineering').", max_length=100)),
                ('region', models.CharField(blank=True, help_text="Region for ABAC scoping (e.g., 'US-East', 'CA-ON').", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive memberships are ignored for permission checks.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration for time-boxed access (e.g., external accountants).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memberships', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace Membership',
                'verbose_name_plural': 'Workspace Memberships',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'business'), name='unique_user_business_membership')],
            },
        ),
    ]
