# Generated by Django for RBAC v1 backfill
from django.db import migrations


def backfill_owner_memberships(apps, schema_editor):
    """
    Backfill WorkspaceMembership for existing Business owners.
    
    Each Business.owner_user gets an OWNER membership so existing users
    retain full access after RBAC is enabled.
    """
    Business = apps.get_model("core", "Business")
    WorkspaceMembership = apps.get_model("core", "WorkspaceMembership")
    
    for business in Business.objects.all():
        if business.owner_user_id:
            WorkspaceMembership.objects.get_or_create(
                user_id=business.owner_user_id,
                business=business,
                defaults={
                    "role": "OWNER",
                    "is_active": True,
                }
            )


def reverse_backfill(apps, schema_editor):
    """
    Remove auto-created OWNER memberships (but keep manually created ones).
    This is a no-op for safety - we don't want to accidentally remove memberships.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_workspace_membership"),
    ]

    operations = [
        migrations.RunPython(backfill_owner_memberships, reverse_backfill),
    ]
