# Generated by OpenAI Codex on 2025-12-16

from django.db import migrations


BUILTIN_ROLE_LABELS = {
    "OWNER": "Owner",
    "SYSTEM_ADMIN": "System Admin",
    "CONTROLLER": "Controller",
    "CASH_MANAGER": "Cash Manager",
    "AP_SPECIALIST": "AP Specialist",
    "AR_SPECIALIST": "AR Specialist",
    "BOOKKEEPER": "Bookkeeper",
    "VIEW_ONLY": "View Only",
    "EXTERNAL_ACCOUNTANT": "External Accountant",
    "AUDITOR": "Auditor",
}

ACTION_CANONICAL = {
    # Lift sensitive balance action into the v2 taxonomy.
    "bank.view_balance": "bank.accounts.view_balance",
}


def _guess_level(action: str) -> str:
    action = action or ""
    if any(
        token in action
        for token in (
            ".approve",
            ".pay",
            ".file_return",
            ".close_period",
            ".delete",
            ".remove",
            ".reset",
            "manage_roles",
            "workspace.delete",
            "workspace.billing",
        )
    ):
        return "approve"
    if any(
        token in action
        for token in (
            ".create",
            ".edit",
            ".manage",
            ".import",
            ".upload",
            ".invite",
            ".settings",
            ".catalog",
            ".actions",
            "journal_entry",
        )
    ):
        return "edit"
    return "view"


def seed_role_definitions(apps, schema_editor):
    Business = apps.get_model("core", "Business")
    WorkspaceMembership = apps.get_model("core", "WorkspaceMembership")
    RoleDefinition = apps.get_model("core", "RoleDefinition")

    # Import RBAC v1 permission mapping as the seed source.
    # We store them as v2 role definitions with level + scope metadata.
    from core.permissions import PERMISSIONS

    businesses = Business.objects.all().only("id", "name")
    for business in businesses.iterator():
        # Ensure built-ins exist
        role_defs_by_key = {}
        for key, label in BUILTIN_ROLE_LABELS.items():
            role_def, _created = RoleDefinition.objects.get_or_create(
                business_id=business.id,
                key=key,
                defaults={
                    "label": label,
                    "is_builtin": True,
                    "permissions": {},
                },
            )
            role_defs_by_key[key] = role_def

        # Seed permissions from v1 mapping
        # PERMISSIONS is: action -> set(RoleEnum) with .value matching our keys
        permissions_by_key = {key: dict(role_defs_by_key[key].permissions or {}) for key in role_defs_by_key}
        for action, roles in (PERMISSIONS or {}).items():
            canonical_action = ACTION_CANONICAL.get(action, action)
            level = _guess_level(canonical_action)
            for role_enum in roles:
                role_key = getattr(role_enum, "value", None) or str(role_enum)
                if role_key not in permissions_by_key:
                    continue
                permissions_by_key[role_key][canonical_action] = {"level": level, "scope": {"type": "all"}}

        for role_key, permissions in permissions_by_key.items():
            RoleDefinition.objects.filter(id=role_defs_by_key[role_key].id).update(permissions=permissions)

        # Backfill membership.role_definition for this business
        for role_key, role_def in role_defs_by_key.items():
            WorkspaceMembership.objects.filter(
                business_id=business.id,
                role=role_key,
                role_definition_id__isnull=True,
            ).update(role_definition_id=role_def.id)


def unseed_role_definitions(apps, schema_editor):
    RoleDefinition = apps.get_model("core", "RoleDefinition")
    RoleDefinition.objects.filter(is_builtin=True, key__in=list(BUILTIN_ROLE_LABELS.keys())).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_userpermissionoverride_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_role_definitions, unseed_role_definitions),
    ]
