# Generated by Django 5.2.8 on 2025-12-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_workspacemembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankrule',
            name='bank_text_pattern',
            field=models.CharField(blank=True, default='', help_text='Pattern to match raw bank feed text (often cryptic bank codes)', max_length=255),
        ),
        migrations.AddField(
            model_name='bankrule',
            name='description_pattern',
            field=models.CharField(blank=True, default='', help_text='Pattern to match cleansed/user-friendly description', max_length=255),
        ),
        migrations.AlterField(
            model_name='bankrule',
            name='pattern',
            field=models.CharField(default='', help_text='Legacy: Regex or substring to match description', max_length=255),
        ),
    ]
