# Generated by Django 5.2.8 on 2025-12-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_add_bank_rule_pattern_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankrule',
            name='auto_categorize_on_import',
            field=models.BooleanField(default=False, help_text='Apply this rule automatically when transactions are imported (no user confirmation needed)'),
        ),
        migrations.AddField(
            model_name='bankrule',
            name='last_applied_count',
            field=models.IntegerField(default=0, help_text='Number of times this rule has been auto-applied'),
        ),
    ]
