# Generated by Django 5.2.8 on 2025-12-16 11:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversals', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='allocation',
            new_name='reversals_a_busines_006c1e_idx',
            old_name='reversals_a_business_b68e1d_idx',
        ),
        migrations.RenameIndex(
            model_name='allocation',
            new_name='reversals_a_busines_e37d8d_idx',
            old_name='reversals_a_business_c539b3_idx',
        ),
        migrations.RenameIndex(
            model_name='customercreditmemo',
            new_name='reversals_c_busines_c2cf1f_idx',
            old_name='reversals_c_business_0f586d_idx',
        ),
        migrations.RenameIndex(
            model_name='customercreditmemo',
            new_name='reversals_c_busines_4775d8_idx',
            old_name='reversals_c_business_50750a_idx',
        ),
        migrations.RenameIndex(
            model_name='customerdeposit',
            new_name='reversals_c_busines_f2ecdd_idx',
            old_name='reversals_c_business_995880_idx',
        ),
        migrations.RenameIndex(
            model_name='customerdeposit',
            new_name='reversals_c_busines_8433e3_idx',
            old_name='reversals_c_business_55371d_idx',
        ),
        migrations.RenameIndex(
            model_name='customerrefund',
            new_name='reversals_c_busines_5303d9_idx',
            old_name='reversals_c_business_465d59_idx',
        ),
        migrations.RenameIndex(
            model_name='customerrefund',
            new_name='reversals_c_busines_91bc06_idx',
            old_name='reversals_c_business_5804c4_idx',
        ),
        migrations.AlterField(
            model_name='customercreditmemo',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='customercreditmemo',
            name='net_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='customercreditmemo',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
