# Generated by Django 5.2.8 on 2025-11-16 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.item', verbose_name='Product / service'),
        ),
    ]
