# Generated by Django 5.2.8 on 2025-11-16 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_category_code_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Optional short code like 1010, 4010, etc.', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.business')),
                ('parent', models.ForeignKey(blank=True, help_text="Optional parent for grouping (e.g. 'Expenses' → 'Software').", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.account')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['type', 'code', 'name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Underlying accounting account for this category.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='core.account'),
        ),
        migrations.AddField(
            model_name='item',
            name='expense_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'EXPENSE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_expense', to='core.account'),
        ),
        migrations.AddField(
            model_name='item',
            name='income_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'INCOME'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_income', to='core.account'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('business', 'code'), name='unique_account_code_per_business'),
        ),
    ]
