# Generated by Django 5.2.8 on 2025-11-17 14:08

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_bankstatementimport_file_format'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bankaccount",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="usage_role",
            field=models.CharField(
                choices=[
                    ("OPERATING", "Operating / checking"),
                    ("SAVINGS", "Savings"),
                    ("CREDIT_CARD", "Credit card"),
                    ("WALLET", "Payment wallet"),
                    ("OTHER", "Other"),
                ],
                default="OPERATING",
                help_text="How you use this account in your business.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="account",
            field=models.OneToOneField(
                blank=True,
                help_text="Ledger account used for balances (optional in v1).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_account",
                to="core.account",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bankaccount",
            unique_together={("business", "name")},
        ),
    ]
