# Generated by Django 5.2.8 on 2025-11-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_bankaccount_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number_mask',
            field=models.CharField(blank=True, help_text="Last 4 digits, e.g. '1234'", max_length=4),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(blank=True, help_text="e.g. 'RBC', 'TD', 'Wise'", max_length=255),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(help_text="e.g. 'RBC Business Checking'", max_length=255),
        ),
    ]
