# Generated by Django 5.2.8 on 2025-11-17 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _populate_bank_import_business(apps, schema_editor):
    BankStatementImport = apps.get_model("core", "BankStatementImport")
    BankAccount = apps.get_model("core", "BankAccount")
    for bank_import in BankStatementImport.objects.all():
        if bank_import.business_id:
            continue
        bank_account = BankAccount.objects.filter(pk=bank_import.bank_account_id).first()
        if bank_account:
            bank_import.business_id = bank_account.business_id
            bank_import.save(update_fields=["business"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_bankaccount_account_number_mask_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankstatementimport',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_imports', to='core.business'),
        ),
        migrations.AlterField(
            model_name='bankstatementimport',
            name='file_format',
            field=models.CharField(choices=[('GENERIC_DATE_DESC_AMOUNT', 'Generic: Date, Description, Amount'), ('GENERIC_DATE_DESC_DEBIT_CREDIT', 'Generic: Date, Description, Debit/Credit')], default='GENERIC_DATE_DESC_AMOUNT', max_length=50),
        ),
        migrations.AlterField(
            model_name='bankstatementimport',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(_populate_bank_import_business, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='bankstatementimport',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_imports', to='core.business'),
        ),
    ]
