# Generated by Django 5.2.8 on 2025-11-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_bankstatementimport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
