# Generated by Django 5.2.8 on 2025-11-26 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_bankrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankrule',
            name='category_label',
        ),
        migrations.AddField(
            model_name='bankrule',
            name='auto_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankrule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_rules', to='core.category'),
        ),
        migrations.AddField(
            model_name='bankrule',
            name='pattern',
            field=models.CharField(default='', help_text='Regex or substring to match description', max_length=255),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='normalized_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Hash for deduplication (date + amount + description)', max_length=64),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='suggestion_confidence',
            field=models.IntegerField(blank=True, help_text='0-100 confidence score from suggestion engine', null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='suggestion_reason',
            field=models.TextField(blank=True, help_text='Explanation for the suggestion'),
        ),
        migrations.AlterField(
            model_name='bankrule',
            name='merchant_name',
            field=models.CharField(help_text='Name to display/match', max_length=255),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('SUGGESTED', 'Suggested'), ('PARTIAL', 'Partially allocated'), ('MATCHED', 'Matched'), ('RECONCILED', 'Reconciled'), ('EXCLUDED', 'Excluded')], db_index=True, default='NEW', max_length=20),
        ),
    ]
