# Generated by Django 5.2.8 on 2025-11-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_business_bank_setup_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='reconciliation_status',
            field=models.CharField(choices=[('unreconciled', 'Unreconciled'), ('reconciled', 'Reconciled')], db_index=True, default='unreconciled', max_length=20),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('SUGGESTED', 'Suggested'), ('PARTIAL', 'Partially allocated'), ('MATCHED_SINGLE', 'Matched (single)'), ('MATCHED_MULTI', 'Matched (split)'), ('LEGACY_CREATED', 'Created (legacy)'), ('MATCHED', 'Matched'), ('RECONCILED', 'Reconciled'), ('EXCLUDED', 'Excluded')], db_index=True, default='NEW', max_length=20),
        ),
    ]
