# Generated by Django 5.2.8 on 2025-12-02 08:05
# Modified to add email_token WITHOUT unique constraint first

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_business_internal_admin_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='email_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='email_to',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        # Add email_token WITHOUT unique constraint first
        migrations.AddField(
            model_name='invoice',
            name='email_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
