# Generated by Django 5.2.8 on 2025-12-02 08:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031b_make_email_token_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='email_last_error',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.CreateModel(
            name='InvoiceEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('to_email', models.EmailField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('error', 'Error')], max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('message_preview', models.TextField(blank=True)),
                ('cc_me', models.BooleanField(default=False)),
                ('open_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('opened_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('opened_user_agent', models.CharField(blank=True, max_length=512)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='core.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_template', models.CharField(blank=True, max_length=255)),
                ('body_template', models.TextField(blank=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_email_template', to='core.business')),
            ],
        ),
    ]
