# Generated by Django 5.2.8 on 2025-12-04 00:00

from django.db import migrations, models


def copy_default_flags(apps, schema_editor):
    TaxRate = apps.get_model("core", "TaxRate")
    for rate in TaxRate.objects.all():
        update_fields = []
        if rate.is_default_sales and not rate.is_default_sales_rate:
            rate.is_default_sales_rate = True
            update_fields.append("is_default_sales_rate")
        if rate.is_default_purchases and not rate.is_default_purchase_rate:
            rate.is_default_purchase_rate = True
            update_fields.append("is_default_purchase_rate")
        if update_fields:
            rate.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_business_email_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="is_tax_registered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="business",
            name="tax_country",
            field=models.CharField(blank=True, default="CA", max_length=2),
        ),
        migrations.AddField(
            model_name="business",
            name="tax_region",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="taxrate",
            name="applies_to_purchases",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="taxrate",
            name="applies_to_sales",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="taxrate",
            name="is_default_purchase_rate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taxrate",
            name="is_default_sales_rate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taxrate",
            name="region",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.RunPython(copy_default_flags, migrations.RunPython.noop),
    ]
