# Generated by Django 5.2.8 on 2025-12-08 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_account_is_suspense'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanionStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_json', models.JSONField(default=dict, help_text='Shape: {overall_summary: str, timeline_bullets: list[str]}')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('data_fingerprint', models.CharField(blank=True, help_text='Hash of input data used to generate this story', max_length=64)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companion_story', to='core.business')),
            ],
            options={
                'verbose_name': 'Companion Story',
                'verbose_name_plural': 'Companion Stories',
            },
        ),
        migrations.CreateModel(
            name='CompanionStoryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_regeneration', models.BooleanField(default=False)),
                ('last_requested_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companion_story_state', to='core.business')),
            ],
            options={
                'verbose_name': 'Companion Story State',
                'verbose_name_plural': 'Companion Story States',
            },
        ),
    ]
