# Generated by Django 5.2.8 on 2025-12-11 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0047_companion_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighRiskAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('is_bulk_adjustment', models.BooleanField(default=False)),
                ('verdict', models.CharField(choices=[('ok', 'OK'), ('warn', 'Warn'), ('fail', 'Fail'), ('skip', 'Skip')], default='ok', max_length=8)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('raw_model_response', models.JSONField(blank=True, default=dict)),
                ('model_profile', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_risk_audits', to='core.business')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
