# Generated by Django 5.2.8 on 2025-12-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_business_tax_filing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="default_nexus_jurisdictions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of jurisdiction codes where the business collects sales tax (e.g. ['US-CA','US-NY']).",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="gst_hst_number",
            field=models.CharField(
                blank=True,
                help_text="Canadian GST/HST registration number (e.g. 123456789RT0001).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="qst_number",
            field=models.CharField(
                blank=True,
                help_text="Quebec QST registration number (e.g. 1234567890TQ0001).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="us_sales_tax_id",
            field=models.CharField(
                blank=True,
                help_text="US state sales tax permit or registration ID.",
                max_length=40,
            ),
        ),
    ]
