# Generated by Django 5.2.8 on 2025-12-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_invoice_place_of_supply_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="tax_regime_ca",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GST_ONLY", "GST only"),
                    ("HST_ONLY", "HST only (HST province)"),
                    ("GST_QST", "GST + QST (Quebec)"),
                    ("GST_PST", "GST + PST (non-harmonized)"),
                ],
                help_text="Only relevant when tax_country = 'CA'.",
                max_length=16,
                null=True,
            ),
        ),
    ]

