# Generated by Django 5.2.8 on 2025-12-16 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_backfill_owner_memberships'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=128)),
                ('effect', models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny')], max_length=8)),
                ('level_override', models.CharField(blank=True, choices=[('none', 'None'), ('view', 'View'), ('edit', 'Edit'), ('approve', 'Approve')], help_text='Optional override level (none/view/edit/approve).', max_length=16, null=True)),
                ('scope_override', models.JSONField(blank=True, help_text='Optional scope override JSON.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['action'],
            },
        ),
        migrations.AddField(
            model_name='workspacemembership',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='ABAC attributes for scoping (e.g. department, region).'),
        ),
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable key (e.g. OWNER, CONTROLLER, custom_slug).', max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('is_builtin', models.BooleanField(default=False, help_text='Built-in roles cannot be deleted.')),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Dict: action -> {"level": "none|view|edit|approve", "scope": {...}}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_definitions', to='core.business')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='workspacemembership',
            name='role_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='core.roledefinition'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['business', 'is_active'], name='core_worksp_busines_a650fe_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['user', 'is_active'], name='core_worksp_user_id_a91c12_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['business', 'role'], name='core_worksp_busines_61c454_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['business', 'role_definition'], name='core_worksp_busines_2e5b54_idx'),
        ),
        migrations.AddField(
            model_name='userpermissionoverride',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='core.workspacemembership'),
        ),
        migrations.AddIndex(
            model_name='roledefinition',
            index=models.Index(fields=['business', 'is_builtin'], name='core_rolede_busines_293cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='roledefinition',
            index=models.Index(fields=['business', 'key'], name='core_rolede_busines_b6bf73_idx'),
        ),
        migrations.AddConstraint(
            model_name='roledefinition',
            constraint=models.UniqueConstraint(fields=('business', 'key'), name='unique_role_definition_per_business'),
        ),
        migrations.AddIndex(
            model_name='userpermissionoverride',
            index=models.Index(fields=['membership', 'effect'], name='core_userpe_members_8904ff_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermissionoverride',
            index=models.Index(fields=['membership', 'action'], name='core_userpe_members_ab8e52_idx'),
        ),
        migrations.AddConstraint(
            model_name='userpermissionoverride',
            constraint=models.UniqueConstraint(fields=('membership', 'action'), name='unique_permission_override_per_membership_action'),
        ),
    ]
