# Generated by Django 5.2.8 on 2025-12-19

from __future__ import annotations

from django.db import migrations


def _ensure_action(perms: dict, action: str, *, level: str) -> dict:
    if not isinstance(perms, dict):
        perms = {}
    if action in perms:
        return perms
    perms[action] = {"level": level, "scope": {"type": "all"}}
    return perms


def forwards(apps, schema_editor) -> None:
    RoleDefinition = apps.get_model("core", "RoleDefinition")

    for role_def in RoleDefinition.objects.all().iterator():
        perms = role_def.permissions if isinstance(role_def.permissions, dict) else {}
        if role_def.key in {"OWNER", "CONTROLLER", "BOOKKEEPER"}:
            perms = _ensure_action(perms, "companion.shadow.write", level="edit")
        if role_def.key in {"OWNER", "CONTROLLER"}:
            perms = _ensure_action(perms, "companion.shadow.wipe", level="approve")

        # Bot role definition: minimal permissions.
        if role_def.key == "JUNIOR_ACCOUNTANT_BOT":
            perms = _ensure_action(perms, "companion.shadow.write", level="edit")
            perms = _ensure_action(perms, "companion.view", level="view")

        RoleDefinition.objects.filter(id=role_def.id).update(permissions=perms)


def backwards(apps, schema_editor) -> None:
    RoleDefinition = apps.get_model("core", "RoleDefinition")
    for role_def in RoleDefinition.objects.all().iterator():
        perms = role_def.permissions if isinstance(role_def.permissions, dict) else {}
        if "companion.shadow.write" in perms:
            perms.pop("companion.shadow.write", None)
        if "companion.shadow.wipe" in perms:
            perms.pop("companion.shadow.wipe", None)
        RoleDefinition.objects.filter(id=role_def.id).update(permissions=perms)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_seed_role_definitions"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]

