# Generated by Django 5.2.8 on 2025-12-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_companion_shadow_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemembership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('SYSTEM_ADMIN', 'System Admin'), ('CONTROLLER', 'Controller'), ('CASH_MANAGER', 'Cash Manager'), ('AP_SPECIALIST', 'AP Specialist'), ('AR_SPECIALIST', 'AR Specialist'), ('BOOKKEEPER', 'Bookkeeper'), ('VIEW_ONLY', 'View Only'), ('EXTERNAL_ACCOUNTANT', 'External Accountant'), ('AUDITOR', 'Auditor'), ('JUNIOR_ACCOUNTANT_BOT', 'Junior Accountant Bot')], default='BOOKKEEPER', max_length=32),
        ),
    ]
