# Generated by Django 5.2.8 on 2025-12-16 19:22

import django.db.models.deletion
import internal_admin.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_admin', '0004_rename_internal_ad_object_0ca4ef_idx_internal_ad_object__57367f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, help_text='Optional: restrict invite to specific email address', max_length=254)),
                ('role', models.CharField(choices=[('SUPPORT', 'Support'), ('OPS', 'Ops'), ('ENGINEERING', 'Engineering'), ('SUPERADMIN', 'Superadmin')], default='SUPPORT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=internal_admin.models._default_invite_expiry)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='0 = unlimited')),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_invites_created', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_invites_used', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expires_at', 'is_active'], name='internal_ad_expires_6964c8_idx')],
            },
        ),
    ]
