# Generated by Django 5.2.8 on 2025-12-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_admin', '0008_adminapprovalrequest_execution_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminauditlog',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Correlation ID for tracing a request across logs', max_length=128),
        ),
    ]
