# Generated by Django 5.2.8 on 2025-12-19 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_admin', '0009_adminauditlog_request_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBreakGlassGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('APPROVAL_SENSITIVE', 'Approval Sensitive Data')], db_index=True, max_length=40)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_glass_grants', to=settings.AUTH_USER_MODEL)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='break_glass_grants', to='internal_admin.adminapprovalrequest')),
            ],
            options={
                'indexes': [models.Index(fields=['admin_user', 'scope', 'expires_at'], name='internal_ad_admin_u_ada9c1_idx'), models.Index(fields=['approval_request', 'expires_at'], name='internal_ad_approva_e881d3_idx')],
            },
        ),
    ]
