# Generated by Django 5.2.8 on 2025-12-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0008_seed_core_jurisdictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxperiodsnapshot',
            name='filed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
