# Generated by Django 5.2.8 on 2025-12-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0013_seed_sample_us_locals'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrate',
            name='is_compound',
            field=models.BooleanField(default=False, help_text='Reserved for future compound-stack handling; calculation is currently controlled by TaxGroup.calculation_method.'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
