# Generated by Django 5.2.8 on 2025-12-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0014_taxrate_is_compound_taxrate_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxproductrule',
            name='ssuta_code',
            field=models.CharField(blank=True, default='', help_text='Optional SSUTA product category code (for future standardized mapping).', max_length=64),
        ),
    ]
