# Generated by Django 5.2.8 on 2025-12-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_invoice_place_of_supply_fields"),
        ("taxes", "0016_tax_payments_and_snapshot_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxpayment",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tax_payments",
                to="core.bankaccount",
            ),
        ),
    ]

