# Generated by Django 5.2.8 on 2025-12-14 00:00

from django.db import migrations, models
from django.db.models import Sum


def backfill_taxgroup_reporting_category(apps, schema_editor):
    TaxGroup = apps.get_model("taxes", "TaxGroup")
    TaxGroupComponent = apps.get_model("taxes", "TaxGroupComponent")

    # Conservative backfill:
    # - If a group has no components at all, treat it as "out of scope".
    group_ids_with_components = TaxGroupComponent.objects.values_list("group_id", flat=True).distinct()
    TaxGroup.objects.exclude(id__in=group_ids_with_components).update(reporting_category="OUT_OF_SCOPE")

    # Best-effort classification for 0%-rate groups based on display name hints.
    # This is intentionally conservative; anything ambiguous remains "TAXABLE" and can be edited in UI.
    try:
        zero_rate_groups = (
            TaxGroup.objects.filter(id__in=group_ids_with_components)
            .annotate(total_rate=Sum("components__rate_percentage"))
            .filter(total_rate=0)
            .only("id", "display_name")
        )
    except Exception:
        return

    ids_by_category: dict[str, list] = {}
    for group in zero_rate_groups:
        name = (group.display_name or "").lower()
        if "out of scope" in name or "out-of-scope" in name:
            ids_by_category.setdefault("OUT_OF_SCOPE", []).append(group.id)
        elif "exempt" in name:
            ids_by_category.setdefault("EXEMPT", []).append(group.id)
        elif "zero" in name or "0%" in name:
            ids_by_category.setdefault("ZERO_RATED", []).append(group.id)

    for category, ids in ids_by_category.items():
        TaxGroup.objects.filter(id__in=ids).update(reporting_category=category)


class Migration(migrations.Migration):

    dependencies = [
        ("taxes", "0017_taxpayment_bank_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxgroup",
            name="reporting_category",
            field=models.CharField(
                choices=[
                    ("TAXABLE", "Taxable / Standard"),
                    ("ZERO_RATED", "Zero-rated (0%)"),
                    ("EXEMPT", "Exempt supply"),
                    ("OUT_OF_SCOPE", "Out of scope (non-GST/HST)"),
                ],
                default="TAXABLE",
                help_text="Canonical reporting category (taxable/zero-rated/exempt/out-of-scope).",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_taxgroup_reporting_category, migrations.RunPython.noop),
    ]

