# Generated by Django 5.2.8 on 2025-12-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0018_taxgroup_reporting_category'),
        ('taxes', '0018_taxpayment_kind_and_bank_label'),
    ]

    operations = [
    ]
