# Generated by Django 5.2.8 on 2025-11-21 08:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0022_business_fiscal_year_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('rate_percentage', models.DecimalField(decimal_places=6, help_text='Stored as decimal (0.05 for 5%).', max_digits=9)),
                ('authority', models.CharField(help_text="Issuing authority code, e.g., 'CRA', 'RQ', 'US-NY'.", max_length=32)),
                ('is_recoverable', models.BooleanField(default=False, help_text='True when the tax can be claimed back (ITC), False when it is non-recoverable.')),
                ('effective_start_date', models.DateField(default=django.utils.timezone.now, help_text='Start date for this rate record.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_components', to='core.business')),
                ('default_coa_account', models.ForeignKey(help_text='Default ledger account (e.g., 2300 liability or 1400 recoverable asset).', on_delete=django.db.models.deletion.PROTECT, related_name='tax_components', to='core.account')),
            ],
            options={
                'ordering': ['business', 'name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TaxGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=128)),
                ('is_system_locked', models.BooleanField(default=False, help_text='True for built-in groups that should not be edited.')),
                ('calculation_method', models.CharField(choices=[('SIMPLE', 'Simple (all components on base)'), ('COMPOUND', 'Compound/stacked')], default='SIMPLE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_groups', to='core.business')),
            ],
            options={
                'ordering': ['business', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='TaxGroupComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculation_order', models.PositiveSmallIntegerField(default=1, help_text='Order 1..n for stacked calculations.')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_components', to='taxes.taxcomponent')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_components', to='taxes.taxgroup')),
            ],
            options={
                'ordering': ['group', 'calculation_order'],
                'unique_together': {('group', 'component')},
            },
        ),
        migrations.AddField(
            model_name='taxgroup',
            name='components',
            field=models.ManyToManyField(related_name='tax_groups', through='taxes.TaxGroupComponent', to='taxes.taxcomponent'),
        ),
        migrations.AlterUniqueTogether(
            name='taxgroup',
            unique_together={('business', 'display_name')},
        ),
        migrations.CreateModel(
            name='TransactionLineTaxDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_line_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('taxable_amount_txn_currency', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('taxable_amount_home_currency_cad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('tax_amount_txn_currency', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('tax_amount_home_currency_cad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('is_recoverable', models.BooleanField(help_text='Snapshot of TaxComponent.is_recoverable at calculation time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_details', to='core.business')),
                ('tax_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_details', to='taxes.taxcomponent')),
                ('tax_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_details', to='taxes.taxgroup')),
                ('transaction_line_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_line_content_type', 'transaction_line_object_id'], name='tax_detail_line_idx')],
            },
        ),
    ]
