# Generated by Django 5.2.8 on 2025-11-21 08:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_seed_canadian_tax_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate_decimal', models.DecimalField(decimal_places=6, help_text='Decimal form (0.05 for 5%).', max_digits=9)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('product_category', models.CharField(choices=[('STANDARD', 'Standard'), ('SAAS', 'SaaS'), ('DIGITAL_GOOD', 'Digital good'), ('ZERO_RATED', 'Zero-rated')], default='STANDARD', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='taxes.taxcomponent')),
            ],
            options={
                'ordering': ['component', 'effective_from'],
                'indexes': [models.Index(fields=['component', 'product_category', 'effective_from', 'effective_to'], name='tr_comp_cat_date_idx')],
            },
        ),
    ]
