# Generated by Django 5.2.8 on 2025-11-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0003_taxrate'),
    ]

    def _backfill_tax_rates(apps, schema_editor):
        TaxComponent = apps.get_model("taxes", "TaxComponent")
        TaxRate = apps.get_model("taxes", "TaxRate")

        for component in TaxComponent.objects.all().iterator():
            TaxRate.objects.get_or_create(
                component=component,
                product_category="STANDARD",
                effective_from=component.effective_start_date,
                defaults={"rate_decimal": component.rate_percentage},
            )

    def _noop(apps, schema_editor):
        # Do not delete tax rates on reverse; leave data intact.
        pass

    operations = [
        migrations.RunPython(_backfill_tax_rates, reverse_code=_noop),
    ]
