# Generated by Django 5.2.8 on 2025-11-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0004_backfill_taxrate_from_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlinetaxdetail',
            name='transaction_date',
            field=models.DateField(blank=True, db_index=True, help_text='Economic event date used for accrual reporting.', null=True),
        ),
    ]
