# Generated by Django 5.2.8 on 2025-12-11 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0006_tax_engine_v1'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcomponent',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, help_text='Optional canonical jurisdiction for this component.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_components', to='taxes.taxjurisdiction'),
        ),
        migrations.AddField(
            model_name='transactionlinetaxdetail',
            name='jurisdiction_code',
            field=models.CharField(blank=True, default='', help_text='Resolved jurisdiction code at calculation time (e.g., CA-ON, US-CA).', max_length=32),
        ),
    ]
