# Generated by Django 5.2.8 on 2025-12-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxes", "0009_taxperiodsnapshot_filed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxgroup",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("ON_TOP", "Tax on top (exclusive)"),
                    ("INCLUDED", "Tax included (inclusive)"),
                ],
                default="ON_TOP",
                help_text="Whether the entered amount is net (ON_TOP) or gross (INCLUDED).",
                max_length=10,
            ),
        ),
    ]

