# Generated by Django 5.2.8 on 2025-12-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxes", "0019_merge_20251214_1134"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionlinetaxdetail",
            name="document_side",
            field=models.CharField(
                blank=True,
                choices=[("SALE", "Sale"), ("PURCHASE", "Purchase")],
                db_index=True,
                default="",
                help_text="Classification for reporting: SALE or PURCHASE. Prefer this over inferring from content type.",
                max_length=8,
            ),
        ),
    ]

