"""
Audit models for findings and reports.

These models support the audit agent's ability to analyze financial data,
detect anomalies, and generate audit reports.
"""

from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from typing import Any, Optional
from uuid import uuid4

from pydantic import BaseModel, Field


class AuditFindingSeverity(str, Enum):
    """Severity level for audit findings."""

    LOW = "low"  # Minor issue, informational
    MEDIUM = "medium"  # Should be addressed
    HIGH = "high"  # Significant issue requiring action
    CRITICAL = "critical"  # Major risk or material misstatement


class AuditFindingType(str, Enum):
    """Type of audit finding."""

    ANOMALY = "anomaly"  # Unusual pattern or outlier
    MISSTATEMENT = "misstatement"  # Incorrect amount
    MISSING_DOCUMENTATION = "missing_documentation"
    POLICY_VIOLATION = "policy_violation"
    CONTROL_WEAKNESS = "control_weakness"
    RECONCILIATION_DIFFERENCE = "reconciliation_difference"
    TREND_DEVIATION = "trend_deviation"
    DUPLICATE = "duplicate"
    TIMING_ISSUE = "timing_issue"
    OTHER = "other"


class AuditFinding(BaseModel):
    """
    A single finding from an audit analysis.

    Represents an issue, anomaly, or observation discovered during
    audit procedures.

    Attributes:
        finding_id: Unique identifier.
        finding_type: Category of finding.
        severity: How serious the finding is.
        title: Short summary.
        description: Detailed explanation.
        account_code: Affected account if applicable.
        account_name: Account name.
        period_start: Start of affected period.
        period_end: End of affected period.
        expected_amount: What the amount should be.
        actual_amount: What the amount actually is.
        difference: The variance.
        percentage_variance: Variance as a percentage.
        affected_transactions: IDs of related transactions.
        evidence: Supporting evidence for the finding.
        recommendation: Suggested remediation.
        management_response: Response from management (if any).
        status: Current status of the finding.
        detected_at: When this was found.
        detected_by: Who/what found it.
    """

    finding_id: str = Field(default_factory=lambda: str(uuid4()))
    finding_type: AuditFindingType
    severity: AuditFindingSeverity
    title: str
    description: str
    account_code: Optional[str] = None
    account_name: Optional[str] = None
    period_start: Optional[date] = None
    period_end: Optional[date] = None
    expected_amount: Optional[Decimal] = None
    actual_amount: Optional[Decimal] = None
    difference: Optional[Decimal] = None
    percentage_variance: Optional[Decimal] = None
    affected_transactions: list[str] = Field(default_factory=list)
    evidence: list[str] = Field(default_factory=list)
    recommendation: Optional[str] = None
    management_response: Optional[str] = None
    status: str = "open"  # open, in_progress, resolved, accepted
    detected_at: datetime = Field(default_factory=datetime.utcnow)
    detected_by: str = "audit_agent"

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat(),
            date: lambda v: v.isoformat(),
            Decimal: lambda v: str(v),
        }

    @property
    def is_material(self) -> bool:
        """Check if this finding is material (high or critical severity)."""
        return self.severity in (
            AuditFindingSeverity.HIGH,
            AuditFindingSeverity.CRITICAL,
        )


class AuditReport(BaseModel):
    """
    A complete audit report generated by the audit agent.

    Summarizes all findings from an audit analysis along with
    conclusions and recommendations.

    Attributes:
        report_id: Unique identifier.
        report_title: Title of the audit report.
        report_type: Type of audit performed.
        business_id: Business that was audited.
        period_start: Start of audit period.
        period_end: End of audit period.
        scope_description: What was included in the audit.
        methodology: How the audit was performed.
        findings: List of all findings.
        summary: Executive summary.
        conclusion: Overall audit conclusion.
        opinion: Audit opinion (if applicable).
        total_findings: Count of all findings.
        critical_findings: Count of critical findings.
        high_findings: Count of high findings.
        total_adjustments: Sum of proposed adjustments.
        recommendations: High-level recommendations.
        prepared_by: Who prepared this report.
        reviewed_by: Who reviewed this report.
        created_at: When the report was created.
        finalized_at: When the report was finalized.
        status: Current status of the report.
    """

    report_id: str = Field(default_factory=lambda: str(uuid4()))
    report_title: str
    report_type: str = "general"  # general, financial, compliance, tax
    business_id: Optional[str] = None
    period_start: date
    period_end: date
    scope_description: Optional[str] = None
    methodology: Optional[str] = None
    findings: list[AuditFinding] = Field(default_factory=list)
    summary: Optional[str] = None
    conclusion: Optional[str] = None
    opinion: Optional[str] = None  # unqualified, qualified, adverse, disclaimer
    total_adjustments: Decimal = Decimal("0")
    recommendations: list[str] = Field(default_factory=list)
    prepared_by: str = "audit_agent"
    reviewed_by: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    finalized_at: Optional[datetime] = None
    status: str = "draft"  # draft, in_review, finalized

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat(),
            date: lambda v: v.isoformat(),
            Decimal: lambda v: str(v),
        }

    @property
    def total_findings(self) -> int:
        """Count of all findings."""
        return len(self.findings)

    @property
    def critical_findings(self) -> int:
        """Count of critical findings."""
        return sum(
            1
            for f in self.findings
            if f.severity == AuditFindingSeverity.CRITICAL
        )

    @property
    def high_findings(self) -> int:
        """Count of high findings."""
        return sum(
            1 for f in self.findings if f.severity == AuditFindingSeverity.HIGH
        )

    @property
    def material_findings(self) -> list[AuditFinding]:
        """Get all material findings."""
        return [f for f in self.findings if f.is_material]

    def add_finding(self, finding: AuditFinding) -> None:
        """Add a finding to this report."""
        self.findings.append(finding)

    def finalize(self, reviewed_by: Optional[str] = None) -> None:
        """Finalize the report."""
        self.status = "finalized"
        self.finalized_at = datetime.utcnow()
        if reviewed_by:
            self.reviewed_by = reviewed_by

    def generate_summary(self) -> str:
        """Generate an executive summary based on findings."""
        total = self.total_findings
        critical = self.critical_findings
        high = self.high_findings

        if total == 0:
            return "No audit findings were identified during this review."

        summary_parts = [
            f"This audit identified {total} finding(s) during the review period "
            f"({self.period_start} to {self.period_end})."
        ]

        if critical > 0:
            summary_parts.append(
                f" {critical} critical finding(s) require immediate attention."
            )
        if high > 0:
            summary_parts.append(
                f" {high} high-priority finding(s) should be addressed promptly."
            )

        return "".join(summary_parts)
