# Generated by Django 5.2.8 on 2025-12-02 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0035_set_tax_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanionInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=16)),
                ('suggested_actions', models.JSONField(default=list)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_insights', to='core.business')),
            ],
        ),
        migrations.CreateModel(
            name='HealthIndexSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('breakdown', models.JSONField(default=dict)),
                ('raw_metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='core.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceCompanionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('enable_health_index', models.BooleanField(default=True)),
                ('enable_suggestions', models.BooleanField(default=True)),
                ('conservatism_level', models.CharField(choices=[('conservative', 'Conservative'), ('standard', 'Standard')], default='conservative', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companion_profile', to='core.business')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_memory', to='core.business')),
            ],
            options={
                'unique_together': {('workspace', 'key')},
            },
        ),
    ]
