# Generated by Django 5.2.8 on 2025-12-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0003_companionsuggestedaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='companioninsight',
            name='context',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('bank', 'Bank'), ('reconciliation', 'Reconciliation'), ('invoices', 'Invoices'), ('expenses', 'Expenses'), ('reports', 'Reports'), ('tax_fx', 'Tax & FX')], default='dashboard', max_length=32),
        ),
        migrations.AddField(
            model_name='companionsuggestedaction',
            name='context',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('bank', 'Bank'), ('reconciliation', 'Reconciliation'), ('invoices', 'Invoices'), ('expenses', 'Expenses'), ('reports', 'Reports'), ('tax_fx', 'Tax & FX')], default='dashboard', max_length=32),
        ),
        migrations.AlterField(
            model_name='companionsuggestedaction',
            name='action_type',
            field=models.CharField(choices=[('bank_match_review', 'Bank match review'), ('send_invoice_reminder', 'Send invoice reminder'), ('categorize_expenses_batch', 'Categorize expenses batch')], default='bank_match_review', max_length=64),
        ),
    ]
