# Generated by Django 5.2.8 on 2025-12-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0006_companionprofile_last_seen_contexts'),
    ]

    operations = [
        migrations.AddField(
            model_name='companionsuggestedaction',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Info'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='INFO', max_length=12),
        ),
        migrations.AddField(
            model_name='companionsuggestedaction',
            name='short_title',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='companionsuggestedaction',
            name='action_type',
            field=models.CharField(choices=[('bank_match_review', 'Bank match review'), ('send_invoice_reminder', 'Send invoice reminder'), ('categorize_expenses_batch', 'Categorize expenses batch'), ('overdue_invoice_reminders', 'Overdue invoice reminders'), ('uncategorized_expense_review', 'Uncategorized expense review'), ('uncategorized_transactions_cleanup', 'Uncategorized transactions cleanup'), ('reconciliation_period_to_close', 'Reconciliation period to close'), ('inactive_customers_followup', 'Inactive customers follow-up'), ('spike_expense_category_review', 'Expense category spike review'), ('old_unreconciled_investigate', 'Investigate old unreconciled'), ('suspense_balance_review', 'Suspense balance review')], default='bank_match_review', max_length=64),
        ),
    ]
