# Generated by Django 5.2.8 on 2025-12-19 09:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0008_workspacecompanionprofile_last_seen_reports_tax_fx'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0056_seed_role_definitions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICircuitBreakerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breaker', models.CharField(choices=[('kill_switch', 'Kill switch'), ('velocity', 'Velocity'), ('value', 'Value'), ('anomaly', 'Anomaly'), ('trust', 'Trust')], db_index=True, max_length=16)),
                ('action', models.CharField(blank=True, default='', max_length=128)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_breaker_events', to='core.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiality_threshold', models.DecimalField(decimal_places=2, default=1, help_text='Write-off / rounding tolerance for tiny differences (in workspace currency).', max_digits=19)),
                ('risk_appetite', models.CharField(choices=[('conservative', 'Conservative'), ('standard', 'Standard'), ('aggressive', 'Aggressive')], default='standard', max_length=16)),
                ('commingling_risk_vendors', models.JSONField(blank=True, default=list, help_text='Vendors requiring extra friction / mandatory review (e.g. Amazon, Target, Costco).')),
                ('related_entities', models.JSONField(blank=True, default=list, help_text='List of related workspace IDs / entities for intercompany awareness.')),
                ('intercompany_enabled', models.BooleanField(default=False)),
                ('sector_archetype', models.CharField(blank=True, default='', help_text='Industry archetype (SaaS, e-commerce, construction, agency, etc.).', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_policy', to='core.business')),
            ],
        ),
        migrations.CreateModel(
            name='ProvisionalLedgerEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], db_index=True, default='proposed', max_length=16)),
                ('subject_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('actor', models.CharField(default='system_companion_v2', max_length=128)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('logic_trace_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('rationale', models.TextField(blank=True, default='')),
                ('business_profile_constraint', models.CharField(blank=True, default='', max_length=128)),
                ('human_in_the_loop', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shadow_events', to=settings.AUTH_USER_MODEL)),
                ('subject_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shadow_events', to='core.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CanonicalLedgerProvenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('actor', models.CharField(default='system_companion_v2', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_provenance', to='core.business')),
                ('shadow_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_promotions', to='companion.provisionalledgerevent')),
            ],
        ),
        migrations.CreateModel(
            name='AICommandRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(db_index=True, max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.CharField(db_index=True, default='system_companion_v2', max_length=128)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('errored', 'Errored')], db_index=True, default='accepted', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_command_records', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_commands', to='core.business')),
                ('shadow_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_records', to='companion.provisionalledgerevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_enabled', models.BooleanField(default=False)),
                ('ai_mode', models.CharField(choices=[('shadow_only', 'Shadow only'), ('suggest_only', 'Suggest only'), ('drafts', 'Drafts'), ('autopilot_limited', 'Limited autopilot')], db_index=True, default='shadow_only', max_length=32)),
                ('velocity_limit_per_minute', models.PositiveIntegerField(default=120, help_text='If Companion proposes/applies more than this per minute, pause further actions.')),
                ('value_breaker_threshold', models.DecimalField(decimal_places=2, default=5000, help_text='If a single transaction exceeds this absolute amount, force Tier-2 review (no auto-apply).', max_digits=19)),
                ('anomaly_stddev_threshold', models.DecimalField(decimal_places=2, default=3, help_text='If amount is > N stddev from vendor baseline, mark as high risk (proposal only).', max_digits=6)),
                ('trust_downgrade_rejection_rate', models.DecimalField(decimal_places=2, default=0.3, help_text='If user rejects more than this share of suggestions, downgrade from autopilot to suggest-only.', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='core.business')),
            ],
        ),
        migrations.CreateModel(
            name='AIIntegrityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('flagged_items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_integrity_reports', to='core.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'created_at'], name='companion_a_workspa_17e9d8_idx'), models.Index(fields=['workspace', 'period_start', 'period_end'], name='companion_a_workspa_e9b7a9_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'period_start', 'period_end'), name='uniq_ai_integrity_report_period')],
            },
        ),
        migrations.AddIndex(
            model_name='provisionalledgerevent',
            index=models.Index(fields=['workspace', 'status', 'created_at'], name='companion_p_workspa_1517bd_idx'),
        ),
        migrations.AddIndex(
            model_name='provisionalledgerevent',
            index=models.Index(fields=['workspace', 'event_type', 'created_at'], name='companion_p_workspa_e3483c_idx'),
        ),
        migrations.AddIndex(
            model_name='provisionalledgerevent',
            index=models.Index(fields=['workspace', 'subject_content_type', 'subject_object_id'], name='companion_p_workspa_b38874_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalledgerprovenance',
            index=models.Index(fields=['workspace', 'content_type', 'object_id'], name='companion_c_workspa_5dfa97_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalledgerprovenance',
            index=models.Index(fields=['workspace', 'shadow_event'], name='companion_c_workspa_70cbbe_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalledgerprovenance',
            index=models.Index(fields=['workspace', 'created_at'], name='companion_c_workspa_06508c_idx'),
        ),
    ]
