# Generated by Django 5.2.8 on 2025-12-20

from __future__ import annotations

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards(apps, schema_editor) -> None:
    ProvisionalLedgerEvent = apps.get_model("companion", "ProvisionalLedgerEvent")
    AICommandRecord = apps.get_model("companion", "AICommandRecord")

    for event in ProvisionalLedgerEvent.objects.filter(command_id__isnull=True).iterator():
        cmd_id = None
        meta = event.metadata if isinstance(event.metadata, dict) else {}
        if isinstance(meta, dict):
            cmd_id = meta.get("command_id") or meta.get("commandId")

        if not cmd_id and getattr(event, "source_command_id", None):
            record = AICommandRecord.objects.filter(id=event.source_command_id).first()
            payload = record.payload if record and isinstance(record.payload, dict) else {}
            cmd_id = payload.get("command_id") or payload.get("commandId")

        if cmd_id:
            try:
                parsed = uuid.UUID(str(cmd_id))
            except Exception:
                continue
            ProvisionalLedgerEvent.objects.filter(id=event.id).update(command_id=parsed)


def backwards(apps, schema_editor) -> None:
    ProvisionalLedgerEvent = apps.get_model("companion", "ProvisionalLedgerEvent")
    ProvisionalLedgerEvent.objects.update(command_id=None)


class Migration(migrations.Migration):
    dependencies = [
        ("companion", "0010_provisional_events_bank_tx_and_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceaisettings",
            name="kill_switch",
            field=models.BooleanField(
                default=False,
                help_text="Emergency stop for this workspace. When enabled, Companion cannot propose or apply.",
            ),
        ),
        migrations.AddField(
            model_name="provisionalledgerevent",
            name="command_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="canonicalledgerprovenance",
            name="applied_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_canonical_provenance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]

