"""
Reporting models for financial statements and analysis.

These models represent structured financial reports that can be
generated by the reporting agent or other analysis workflows.
"""

from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from typing import Any, Optional
from uuid import uuid4

from pydantic import BaseModel, Field


class AccountRowGroup(str, Enum):
    """Grouping for P&L account rows."""

    INCOME = "INCOME"
    COGS = "COGS"
    EXPENSE = "EXPENSE"


class PlAccountRow(BaseModel):
    """
    A single account row in a Profit & Loss report.

    Represents one line item in the P&L statement with current
    and comparison period amounts.

    Attributes:
        row_id: Unique identifier.
        account_code: Chart of accounts code.
        account_name: Human-readable account name.
        group: Which section this belongs to (INCOME, COGS, EXPENSE).
        amount: Current period amount.
        compare_amount: Comparison period amount (if applicable).
        change_amount: Difference between current and comparison.
        change_percent: Percentage change.
        budget_amount: Budgeted amount (if applicable).
        budget_variance: Variance from budget.
        is_subtotal: Whether this is a subtotal row.
        indent_level: Indentation level for hierarchy.
        children: Child account rows (for hierarchical display).
    """

    row_id: str = Field(default_factory=lambda: str(uuid4()))
    account_code: Optional[str] = None
    account_name: str
    group: AccountRowGroup
    amount: Decimal = Decimal("0")
    compare_amount: Optional[Decimal] = None
    change_amount: Optional[Decimal] = None
    change_percent: Optional[Decimal] = None
    budget_amount: Optional[Decimal] = None
    budget_variance: Optional[Decimal] = None
    is_subtotal: bool = False
    indent_level: int = 0
    children: list["PlAccountRow"] = Field(default_factory=list)

    class Config:
        json_encoders = {Decimal: lambda v: str(v)}

    @property
    def has_comparison(self) -> bool:
        """Check if comparison data is available."""
        return self.compare_amount is not None

    @property
    def has_budget(self) -> bool:
        """Check if budget data is available."""
        return self.budget_amount is not None

    def calculate_change(self) -> None:
        """Calculate change metrics from current and compare amounts."""
        if self.compare_amount is not None:
            self.change_amount = self.amount - self.compare_amount
            if self.compare_amount != 0:
                self.change_percent = (
                    (self.change_amount / abs(self.compare_amount)) * 100
                ).quantize(Decimal("0.01"))

    def calculate_budget_variance(self) -> None:
        """Calculate budget variance."""
        if self.budget_amount is not None:
            self.budget_variance = self.amount - self.budget_amount


class PlReport(BaseModel):
    """
    A complete Profit & Loss report.

    Contains all account rows organized by group (income, COGS, expenses)
    along with calculated totals and key metrics.

    Attributes:
        report_id: Unique identifier.
        business_id: Business this report is for.
        business_name: Business name.
        currency: Currency code.
        period_label: Human-readable period label.
        period_start: Start of reporting period.
        period_end: End of reporting period.
        compare_label: Label for comparison period.
        compare_start: Start of comparison period.
        compare_end: End of comparison period.
        rows: All account rows.
        total_income: Sum of income accounts.
        total_cogs: Sum of COGS accounts.
        gross_profit: Income minus COGS.
        total_expenses: Sum of expense accounts.
        net_income: Gross profit minus expenses.
        gross_margin_pct: Gross profit as % of income.
        net_margin_pct: Net income as % of income.
        compare_total_income: Comparison period income.
        compare_total_cogs: Comparison period COGS.
        compare_gross_profit: Comparison period gross profit.
        compare_total_expenses: Comparison period expenses.
        compare_net_income: Comparison period net income.
        change_income_pct: % change in income.
        change_cogs_pct: % change in COGS.
        change_gross_profit_pct: % change in gross profit.
        change_expenses_pct: % change in expenses.
        change_net_income_pct: % change in net income.
        generated_at: When this report was generated.
        generated_by: What agent/process generated it.
    """

    report_id: str = Field(default_factory=lambda: str(uuid4()))
    business_id: Optional[str] = None
    business_name: str
    currency: str = "USD"
    period_label: str
    period_start: date
    period_end: date
    compare_label: Optional[str] = None
    compare_start: Optional[date] = None
    compare_end: Optional[date] = None
    rows: list[PlAccountRow] = Field(default_factory=list)
    total_income: Decimal = Decimal("0")
    total_cogs: Decimal = Decimal("0")
    gross_profit: Decimal = Decimal("0")
    total_expenses: Decimal = Decimal("0")
    net_income: Decimal = Decimal("0")
    gross_margin_pct: Optional[Decimal] = None
    net_margin_pct: Optional[Decimal] = None
    compare_total_income: Optional[Decimal] = None
    compare_total_cogs: Optional[Decimal] = None
    compare_gross_profit: Optional[Decimal] = None
    compare_total_expenses: Optional[Decimal] = None
    compare_net_income: Optional[Decimal] = None
    change_income_pct: Optional[Decimal] = None
    change_cogs_pct: Optional[Decimal] = None
    change_gross_profit_pct: Optional[Decimal] = None
    change_expenses_pct: Optional[Decimal] = None
    change_net_income_pct: Optional[Decimal] = None
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    generated_by: str = "reporting_agent"

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat(),
            date: lambda v: v.isoformat(),
            Decimal: lambda v: str(v),
        }

    @property
    def income_rows(self) -> list[PlAccountRow]:
        """Get all income rows."""
        return [r for r in self.rows if r.group == AccountRowGroup.INCOME]

    @property
    def cogs_rows(self) -> list[PlAccountRow]:
        """Get all COGS rows."""
        return [r for r in self.rows if r.group == AccountRowGroup.COGS]

    @property
    def expense_rows(self) -> list[PlAccountRow]:
        """Get all expense rows."""
        return [r for r in self.rows if r.group == AccountRowGroup.EXPENSE]

    @property
    def has_comparison(self) -> bool:
        """Check if this report has comparison data."""
        return self.compare_label is not None

    @property
    def is_profitable(self) -> bool:
        """Check if net income is positive."""
        return self.net_income > 0

    def calculate_totals(self) -> None:
        """Calculate all totals from row data."""
        self.total_income = sum(
            (r.amount for r in self.income_rows), Decimal("0")
        )
        self.total_cogs = sum((r.amount for r in self.cogs_rows), Decimal("0"))
        self.total_expenses = sum(
            (r.amount for r in self.expense_rows), Decimal("0")
        )
        self.gross_profit = self.total_income - self.total_cogs
        self.net_income = self.gross_profit - self.total_expenses

        # Calculate margins
        if self.total_income > 0:
            self.gross_margin_pct = (
                (self.gross_profit / self.total_income) * 100
            ).quantize(Decimal("0.01"))
            self.net_margin_pct = (
                (self.net_income / self.total_income) * 100
            ).quantize(Decimal("0.01"))

    def calculate_comparison_totals(self) -> None:
        """Calculate comparison totals from row data."""
        self.compare_total_income = sum(
            (r.compare_amount or Decimal("0") for r in self.income_rows),
            Decimal("0"),
        )
        self.compare_total_cogs = sum(
            (r.compare_amount or Decimal("0") for r in self.cogs_rows),
            Decimal("0"),
        )
        self.compare_total_expenses = sum(
            (r.compare_amount or Decimal("0") for r in self.expense_rows),
            Decimal("0"),
        )
        self.compare_gross_profit = (
            self.compare_total_income - self.compare_total_cogs
        )
        self.compare_net_income = (
            self.compare_gross_profit - self.compare_total_expenses
        )

        # Calculate percentage changes
        def pct_change(current: Decimal, previous: Decimal) -> Optional[Decimal]:
            if previous == 0:
                return None
            return ((current - previous) / abs(previous) * 100).quantize(
                Decimal("0.01")
            )

        self.change_income_pct = pct_change(
            self.total_income, self.compare_total_income
        )
        self.change_cogs_pct = pct_change(
            self.total_cogs, self.compare_total_cogs
        )
        self.change_gross_profit_pct = pct_change(
            self.gross_profit, self.compare_gross_profit
        )
        self.change_expenses_pct = pct_change(
            self.total_expenses, self.compare_total_expenses
        )
        self.change_net_income_pct = pct_change(
            self.net_income, self.compare_net_income
        )
