# Generated by Django 5.2.8 on 2025-12-21 10:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0058_alter_workspacemembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('inventory', 'Inventory'), ('non_inventory', 'Non-inventory'), ('service', 'Service'), ('bundle', 'Bundle'), ('assembly', 'Assembly')], db_index=True, default='inventory', max_length=32)),
                ('costing_method', models.CharField(choices=[('fifo', 'FIFO'), ('avco', 'Weighted Average (AVCO)')], db_index=True, default='fifo', max_length=8)),
                ('default_uom', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_account', models.ForeignKey(blank=True, help_text='Inventory asset account (required for inventory/assembly items).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items_asset', to='core.account')),
                ('cogs_account', models.ForeignKey(blank=True, help_text='COGS account (required for inventory/assembly items).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items_cogs', to='core.account')),
                ('revenue_account', models.ForeignKey(blank=True, help_text='Optional revenue account override.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items_revenue', to='core.account')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='core.business')),
            ],
            options={
                'ordering': ['name', 'sku', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=32)),
                ('location_type', models.CharField(choices=[('site', 'Site'), ('bin', 'Bin'), ('in_transit', 'In transit')], db_index=True, default='site', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.inventorylocation')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_locations', to='core.business')),
            ],
            options={
                'ordering': ['name', 'code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('STOCK_RECEIVED', 'Stock received'), ('STOCK_SHIPPED', 'Stock shipped'), ('STOCK_COMMITTED', 'Stock committed'), ('STOCK_UNCOMMITTED', 'Stock uncommitted'), ('STOCK_ADJUSTED', 'Stock adjusted'), ('STOCK_TRANSFERRED', 'Stock transferred'), ('STOCK_LANDED_COST_ALLOCATED', 'Landed cost allocated (stub)')], db_index=True, max_length=64)),
                ('quantity_delta', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('source_reference', models.CharField(blank=True, db_index=True, default='', help_text='External reference (PO, receipt, SO, shipment, etc.).', max_length=255)),
                ('batch_reference', models.CharField(blank=True, db_index=True, default='', help_text='FIFO batch identifier (optional).', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor_type', models.CharField(blank=True, default='', max_length=32)),
                ('actor_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_events', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_events', to='core.business')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='inventory.inventoryitem')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='inventory.inventorylocation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_on_hand', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('qty_committed', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('qty_on_order', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('qty_available', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('last_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='core.business')),
                ('last_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.inventoryevent')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.inventoryitem')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.inventorylocation')),
            ],
            options={
                'ordering': ['item_id', 'location_id'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['workspace', 'item_type', 'is_active'], name='inventory_i_workspa_fe426c_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('workspace', 'sku'), name='uniq_inventory_item_sku_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='inventorylocation',
            index=models.Index(fields=['workspace', 'location_type'], name='inventory_i_workspa_f83db7_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorylocation',
            constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='uniq_inventory_location_code_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='inventoryevent',
            index=models.Index(fields=['workspace', 'item', 'location', 'created_at'], name='inventory_i_workspa_57b42b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryevent',
            index=models.Index(fields=['workspace', 'event_type', 'created_at'], name='inventory_i_workspa_33e585_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['workspace', 'item'], name='inventory_i_workspa_b68a60_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['workspace', 'location'], name='inventory_i_workspa_be5d84_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.UniqueConstraint(fields=('workspace', 'item', 'location'), name='uniq_inventory_balance_item_location_per_workspace'),
        ),
    ]
