# Generated by Django 5.2.8 on 2025-12-21 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_workspacemembership_role'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.CheckConstraint(condition=models.Q(('qty_on_hand__gte', 0)), name='inventorybalance_qty_on_hand_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.CheckConstraint(condition=models.Q(('qty_committed__gte', 0)), name='inventorybalance_qty_committed_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.CheckConstraint(condition=models.Q(('qty_on_order__gte', 0)), name='inventorybalance_qty_on_order_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='inventoryevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type', 'STOCK_RECEIVED'), ('unit_cost__isnull', False)), models.Q(('event_type', 'STOCK_RECEIVED'), _negated=True), _connector='OR'), name='inventoryevent_received_requires_unit_cost'),
        ),
    ]
