# Generated by Django 5.2.8 on 2025-12-21 11:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_workspacemembership_role'),
        ('inventory', '0002_inventorybalance_inventorybalance_qty_on_hand_gte_0_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryevent',
            name='event_type',
            field=models.CharField(choices=[('PO_CREATED', 'PO created'), ('PO_UPDATED', 'PO updated'), ('PO_CANCELLED', 'PO cancelled'), ('STOCK_RECEIVED', 'Stock received'), ('STOCK_SHIPPED', 'Stock shipped'), ('STOCK_COMMITTED', 'Stock committed'), ('STOCK_UNCOMMITTED', 'Stock uncommitted'), ('STOCK_ADJUSTED', 'Stock adjusted'), ('STOCK_TRANSFERRED', 'Stock transferred'), ('STOCK_LANDED_COST_ALLOCATED', 'Landed cost allocated (stub)'), ('VENDOR_BILL_POSTED', 'Vendor bill posted')], db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='LandedCostBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied'), ('void', 'Void')], db_index=True, default='draft', max_length=16)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('allocation_method', models.CharField(choices=[('value', 'Value'), ('weight', 'Weight'), ('quantity', 'Quantity'), ('manual', 'Manual')], default='manual', max_length=16)),
                ('total_extra_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_landed_cost_batches', to=settings.AUTH_USER_MODEL)),
                ('credit_account', models.ForeignKey(blank=True, help_text='Credit account for landed cost (clearing/AP placeholder).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='landed_cost_batches_credit', to='core.account')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landed_cost_batches', to='core.business')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LandedCostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt_event', models.ForeignKey(help_text='Must be a STOCK_RECEIVED event.', on_delete=django.db.models.deletion.PROTECT, related_name='landed_cost_allocations', to='inventory.inventoryevent')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.landedcostbatch')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PO', 'Purchase Order'), ('BILL', 'Vendor Bill')], db_index=True, max_length=8)),
                ('external_reference', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('void', 'Void')], db_index=True, default='open', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_documents', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_documents', to='core.business')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='inventoryevent',
            name='purchase_document',
            field=models.ForeignKey(blank=True, help_text='Optional purchasing document context (PO/BILL).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_events', to='inventory.purchasedocument'),
        ),
        migrations.CreateModel(
            name='PurchaseDocumentReceiptLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Optional partial quantity invoiced; defaults to full receipt quantity when null.', max_digits=19, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(limit_choices_to={'document_type': 'BILL'}, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_links', to='inventory.purchasedocument')),
                ('receipt_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_links', to='inventory.inventoryevent')),
            ],
        ),
        migrations.AddIndex(
            model_name='landedcostbatch',
            index=models.Index(fields=['workspace', 'status', 'created_at'], name='inventory_l_workspa_5102d9_idx'),
        ),
        migrations.AddIndex(
            model_name='landedcostallocation',
            index=models.Index(fields=['batch', 'created_at'], name='inventory_l_batch_i_3da374_idx'),
        ),
        migrations.AddIndex(
            model_name='landedcostallocation',
            index=models.Index(fields=['receipt_event', 'created_at'], name='inventory_l_receipt_06a33f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedocument',
            index=models.Index(fields=['workspace', 'document_type', 'status'], name='inventory_p_workspa_89d025_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchasedocument',
            constraint=models.UniqueConstraint(fields=('workspace', 'document_type', 'external_reference'), name='uniq_purchase_document_type_reference_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='purchasedocumentreceiptlink',
            index=models.Index(fields=['bill', 'created_at'], name='inventory_p_bill_id_47d713_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedocumentreceiptlink',
            index=models.Index(fields=['receipt_event', 'created_at'], name='inventory_p_receipt_011689_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchasedocumentreceiptlink',
            constraint=models.UniqueConstraint(fields=('bill', 'receipt_event'), name='uniq_bill_receipt_event_link'),
        ),
    ]
