# Generated by Django 5.2.8 on 2025-12-14

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0052_business_tax_regime_ca"),
        ("taxes", "0019_merge_20251214_1134"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerCreditMemo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("credit_memo_number", models.CharField(blank=True, default="", max_length=50)),
                ("posting_date", models.DateField(default=django.utils.timezone.now)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("POSTED", "Posted"), ("VOIDED", "Voided")], db_index=True, default="DRAFT", max_length=12)),
                ("memo", models.TextField(blank=True, default="")),
                ("net_total", models.DecimalField(decimal_places=2, default="0.00", max_digits=12)),
                ("tax_total", models.DecimalField(decimal_places=2, default="0.00", max_digits=12)),
                ("grand_total", models.DecimalField(decimal_places=2, default="0.00", max_digits=12)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="customer_credit_memos", to="core.business")),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="credit_memos", to="core.customer")),
                ("source_invoice", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="credit_memos", to="core.invoice")),
                ("tax_group", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="customer_credit_memos", to="taxes.taxgroup")),
            ],
            options={
                "ordering": ["-posting_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CustomerDeposit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("posting_date", models.DateField(default=django.utils.timezone.now)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("POSTED", "Posted"), ("VOIDED", "Voided")], db_index=True, default="DRAFT", max_length=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                ("memo", models.TextField(blank=True, default="")),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bank_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="customer_deposits", to="core.bankaccount")),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="customer_deposits", to="core.business")),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="deposits", to="core.customer")),
            ],
            options={
                "ordering": ["-posting_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CustomerRefund",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("posting_date", models.DateField(default=django.utils.timezone.now)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("POSTED", "Posted"), ("VOIDED", "Voided")], db_index=True, default="DRAFT", max_length=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                ("memo", models.TextField(blank=True, default="")),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bank_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="customer_refunds", to="core.bankaccount")),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="customer_refunds", to="core.business")),
                ("credit_memo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="refunds", to="reversals.customercreditmemo")),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="refunds", to="core.customer")),
                ("deposit", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="refunds", to="reversals.customerdeposit")),
            ],
            options={
                "ordering": ["-posting_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ledger_side", models.CharField(choices=[("CUSTOMER", "Customer (AR)"), ("VENDOR", "Vendor (AP)")], db_index=True, max_length=12)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("VOIDED", "Voided")], db_index=True, default="ACTIVE", max_length=8)),
                ("source_object_id", models.PositiveIntegerField()),
                ("target_object_id", models.PositiveIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                ("operation_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, default="", max_length=255)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="allocations", to="core.business")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="allocations_created", to=settings.AUTH_USER_MODEL)),
                ("source_content_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="contenttypes.contenttype")),
                ("target_content_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="contenttypes.contenttype")),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="customercreditmemo",
            index=models.Index(fields=["business", "customer", "status"], name="reversals_c_business_0f586d_idx"),
        ),
        migrations.AddIndex(
            model_name="customercreditmemo",
            index=models.Index(fields=["business", "posting_date"], name="reversals_c_business_50750a_idx"),
        ),
        migrations.AddIndex(
            model_name="customerdeposit",
            index=models.Index(fields=["business", "customer", "status"], name="reversals_c_business_995880_idx"),
        ),
        migrations.AddIndex(
            model_name="customerdeposit",
            index=models.Index(fields=["business", "posting_date"], name="reversals_c_business_55371d_idx"),
        ),
        migrations.AddIndex(
            model_name="customerrefund",
            index=models.Index(fields=["business", "customer", "status"], name="reversals_c_business_465d59_idx"),
        ),
        migrations.AddIndex(
            model_name="customerrefund",
            index=models.Index(fields=["business", "posting_date"], name="reversals_c_business_5804c4_idx"),
        ),
        migrations.AddIndex(
            model_name="allocation",
            index=models.Index(fields=["business", "source_content_type", "source_object_id"], name="reversals_a_business_b68e1d_idx"),
        ),
        migrations.AddIndex(
            model_name="allocation",
            index=models.Index(fields=["business", "target_content_type", "target_object_id"], name="reversals_a_business_c539b3_idx"),
        ),
        migrations.AddConstraint(
            model_name="customerdeposit",
            constraint=models.CheckConstraint(check=models.Q(amount__gt=0), name="customerdeposit_amount_positive"),
        ),
        migrations.AddConstraint(
            model_name="customerrefund",
            constraint=models.CheckConstraint(check=models.Q(amount__gt=0), name="customerrefund_amount_positive"),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.CheckConstraint(check=models.Q(amount__gt=0), name="allocation_amount_positive"),
        ),
    ]
