# Generated by Django 5.2.8 on 2025-12-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal_admin', '0003_adminauditlog_level_category_featureflag_supportticket'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminauditlog',
            new_name='internal_ad_object__57367f_idx',
            old_name='internal_ad_object_0ca4ef_idx',
        ),
        migrations.RenameIndex(
            model_name='impersonationtoken',
            new_name='internal_ad_admin_i_278341_idx',
            old_name='internal_ad_admin_i_9aa49b_idx',
        ),
        migrations.RenameIndex(
            model_name='impersonationtoken',
            new_name='internal_ad_expires_1b7265_idx',
            old_name='internal_ad_expires_d7bd16_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='internal_ad_status_e46274_idx',
            old_name='internal_ad_status__0033be_idx',
        ),
    ]
