# Generated by Django 5.2.8 on 2025-12-16 20:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_seed_role_definitions'),
        ('internal_admin', '0005_add_admin_invite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('TAX_PERIOD_RESET', 'Reset Tax Period'), ('LEDGER_ADJUST', 'Ledger Adjustment'), ('WORKSPACE_DELETE', 'Delete Workspace'), ('BULK_REFUND', 'Bulk Refund'), ('USER_BAN', 'Ban User'), ('FEATURE_FLAG_CRITICAL', 'Toggle Critical Feature')], db_index=True, max_length=50)),
                ('payload', models.JSONField(default=dict, help_text='Action-specific data (e.g., amounts, IDs, settings)')),
                ('reason', models.TextField(help_text='Justification for the action')),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='Reason for rejection (if rejected)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-expire if not resolved by this time', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='actor_role',
            field=models.CharField(blank=True, choices=[('SUPPORT', 'Support'), ('OPS', 'Ops'), ('ENGINEERING', 'Engineering'), ('SUPERADMIN', 'Superadmin')], db_index=True, default='', help_text='Admin role at time of action', max_length=20),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='user_agent',
            field=models.TextField(blank=True, default='', help_text='Browser/client info'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['actor_role', 'timestamp'], name='internal_ad_actor_r_0d8bac_idx'),
        ),
        migrations.AddField(
            model_name='adminapprovalrequest',
            name='approver_admin',
            field=models.ForeignKey(blank=True, help_text='The admin who approved/rejected (Checker)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminapprovalrequest',
            name='initiator_admin',
            field=models.ForeignKey(help_text='The admin who requested this action (Maker)', on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminapprovalrequest',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text='User affected by this action (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_targeting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminapprovalrequest',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_approval_requests', to='core.business'),
        ),
        migrations.AddIndex(
            model_name='adminapprovalrequest',
            index=models.Index(fields=['status', 'action_type'], name='internal_ad_status_97d4eb_idx'),
        ),
        migrations.AddIndex(
            model_name='adminapprovalrequest',
            index=models.Index(fields=['initiator_admin', 'status'], name='internal_ad_initiat_b52608_idx'),
        ),
    ]
