# Generated by Django 5.2.8 on 2025-12-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_admin', '0007_impersonationtoken_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminapprovalrequest',
            name='execution_error',
            field=models.TextField(blank=True, default='', help_text='Execution error (if failed)'),
        ),
        migrations.AlterField(
            model_name='adminapprovalrequest',
            name='action_type',
            field=models.CharField(choices=[('TAX_PERIOD_RESET', 'Reset Tax Period'), ('LEDGER_ADJUST', 'Ledger Adjustment'), ('WORKSPACE_DELETE', 'Delete Workspace'), ('BULK_REFUND', 'Bulk Refund'), ('USER_BAN', 'Ban User'), ('USER_REACTIVATE', 'Reactivate User'), ('USER_PRIVILEGE_CHANGE', 'Change User Privileges'), ('PASSWORD_RESET_LINK', 'Create Password Reset Link'), ('FEATURE_FLAG_CRITICAL', 'Toggle Critical Feature')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='adminapprovalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminauditlog',
            name='actor_role',
            field=models.CharField(blank=True, choices=[('SUPPORT', 'Support'), ('OPS', 'Ops'), ('ENGINEERING', 'Engineering'), ('SUPERADMIN', 'Superadmin'), ('PRIMARY_ADMIN', 'Primary Admin')], db_index=True, default='', help_text='Admin role at time of action', max_length=20),
        ),
        migrations.AlterField(
            model_name='admininvite',
            name='role',
            field=models.CharField(choices=[('SUPPORT', 'Support'), ('OPS', 'Ops'), ('ENGINEERING', 'Engineering'), ('SUPERADMIN', 'Superadmin'), ('PRIMARY_ADMIN', 'Primary Admin')], default='SUPPORT', max_length=20),
        ),
        migrations.AlterField(
            model_name='internaladminprofile',
            name='role',
            field=models.CharField(choices=[('SUPPORT', 'Support'), ('OPS', 'Ops'), ('ENGINEERING', 'Engineering'), ('SUPERADMIN', 'Superadmin'), ('PRIMARY_ADMIN', 'Primary Admin')], db_index=True, default='SUPPORT', max_length=20),
        ),
    ]
