# Generated by Django 5.2.8 on 2025-12-21 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_admin', '0010_adminbreakglassgrant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, help_text='e.g. Support, Finance, Engineering, Ops', max_length=100)),
                ('admin_panel_access', models.BooleanField(db_index=True, default=False)),
                ('primary_admin_role', models.CharField(choices=[('none', 'None'), ('support', 'Support'), ('finance', 'Finance'), ('engineering', 'Engineering'), ('superadmin', 'Superadmin')], db_index=True, default='none', max_length=50)),
                ('is_active_employee', models.BooleanField(db_index=True, default=True)),
                ('workspace_scope', models.JSONField(blank=True, default=dict, help_text='{"mode": "all" | "region" | "specific", "ids": [workspace_ids], "region": "CA" }')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff profile',
                'verbose_name_plural': 'Staff profiles',
                'indexes': [models.Index(fields=['admin_panel_access', 'is_active_employee'], name='internal_ad_admin_p_08cc64_idx'), models.Index(fields=['primary_admin_role', 'admin_panel_access'], name='internal_ad_primary_5afca3_idx')],
            },
        ),
    ]
